hm6
abramovaE/NewProject pull request #6
Opened 2020-12-13 02:22 UTC by abramovaE

2020-12-13 19:51 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/ActorsAdapter.kt
> +    var actors: List<Actor>? = movie.actors
Может лучше empyList делать, вместо nullable типа

2020-12-13 19:52 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/ActorsAdapter.kt
> +        return actors!!.size;
Чтобы не делать так

2020-12-13 19:53 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/ActorsAdapter.kt
> +        return actors!!.size;
Вообще зачем нужна эта функция, она не используется

2020-12-13 19:56 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/FragmentMovieDetails.kt
> +        reviews.text = "" + " reviews"
Почему не string ресурсы и зачем сложение с пустой строкой?

2020-12-16 08:06 UTC, strorinWind requested changes
my comment

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/ActorsAdapter.kt
> +    var actors: List<Actor>? = movie.actors
В movie это же и так non-null тип

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/MoviesAdapter.kt
> +//
Если код не нужен, его нужно удалить, а не закомментировать

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/MoviesViewHolder.kt
> +        reviews.setText("" + "reviews")
Тоже про ресурсы

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/MoviesViewHolder.kt
> +        dur.setText("" + movie.runtime + " min")
На самом деле это тоже можно сделать через аргументы в ресурсной строке

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/data/JsonLoad.kt
> +package com.android.academy.fundamentals.homework.features.data
Проверь имена пакетов в этой папке

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/data/JsonLoad.kt
> +package com.android.academy.fundamentals.homework.features.data
Они в студии подчеркиваются волнистой линией, можно нажать alt+enter и он предложит исправить

2020-12-16 08:06 UTC, strorinWind commented on app/src/main/java/com/abramovae/newproject/MoviesViewHolder.kt
> +        dur.setText("" + movie.runtime + itemView.context.getString(R.string.min))
Аргументы делаются типа так
<string name="timeFormat">%1$d minutes ago</string>
1 - номер аргумента
d - тип аргумента, для десятичных чисел

И тогда можно обращаться как
        dur.text = itemView.context.getString(R.string.min, movie.runtime)

2020-12-16 19:32 UTC, abramovaE commented on app/src/main/java/com/abramovae/newproject/data/JsonLoad.kt
> +package com.android.academy.fundamentals.homework.features.data
у меня все нормально, ничего не подчеркивается

2020-12-27 08:30 UTC, merged